local const = require "main.const"


function on_input(self, action_id, action)
	if action_id == const.touch and action.pressed then
		local target_pos = vmath.vector3(action.x, action.y, 0)
		factory.create("#shooter", self.spawn_pos, nil, { target = target_pos })
		--print("Shooter target pos", target_pos)
	end
end


function init(self)
	msg.post(".", "acquire_input_focus")
	self.spawn_pos = const.center_point
end

