local const = require "main.const"

local time_elapsed = 0

function update(self, dt)
	time_elapsed = time_elapsed + dt
	if time_elapsed >= 0.3 then
		gui.set_enabled(gui.get_node("awake"), true)
	end
end


function on_input(self, action_id, action)
	if action_id == const.touch then
		sys.exit(0)
	end
end


function init(self)
	msg.post(".", "acquire_input_focus")
	gui.play_flipbook(gui.get_node("you_are"), "anim_you_are")
end
